<?php

define('SMART_DONATIONS_STRIPE_PLUGIN_NAME',dirname(plugin_basename(__FILE__)));
define('SMART_DONATIONS_STRIPE_DIR',WP_PLUGIN_DIR.'/'.SMART_DONATIONS_STRIPE_PLUGIN_NAME);
define('SMART_DONATIONS_STRIPE_PLUGIN_URL', plugin_dir_url(__FILE__));
